using System;

namespace HastTableSearchAndRecursionWithAsync
{
    public class Data
    {
        public void generate(int kiekis, ref HashTableQ hash)
        {
            var name = new[] {
    new { names = "Nora" },
    new { names = "Alec" },
    new { names = "Philip" },
    new { names = "Nell" },
    new { names = "Yardley" },
    new { names = "Jelani" },
    new { names = "Judah" },
    new { names = "Marsden" },
    new { names = "Alana" },
    new { names = "Xandra" },
    new { names = "Ray" },
    new { names = "Sydney" },
    new { names = "Camden" },
    new { names = "Emerald" },
    new { names = "Ayanna" },
    new { names = "Breanna" },
    new { names = "Macy" },
    new { names = "Ulla" },
    new { names = "Cameron" },
    new { names = "Nero" },
    new { names = "Irene" },
    new { names = "Flavia" },
    new { names = "Elmo" },
    new { names = "Aquila" },
    new { names = "Richard" },
    new { names = "Jemima" },
    new { names = "Brenden" },
    new { names = "Mollie" },
    new { names = "Fatima" },
    new { names = "Dexter" },
    new { names = "Adria" },
    new { names = "Derek" },
    new { names = "Jorden" },
    new { names = "Caesar" },
    new { names = "Rudyard" },
    new { names = "Gwendolyn" },
    new { names = "Eaton" },
    new { names = "Susan" },
    new { names = "Sage" },
    new { names = "Buckminster" },
    new { names = "Zena" },
    new { names = "Miriam" },
    new { names = "Doris" },
    new { names = "Tiger" },
    new { names = "Hyacinth" },
    new { names = "Katell" },
    new { names = "Duncan" },
    new { names = "Clark" },
    new { names = "Damian" },
    new { names = "Galvin" },
    new { names = "Nomlanga" },
    new { names = "Gay" },
    new { names = "Vincent" },
    new { names = "Venus" },
    new { names = "Jerome" },
    new { names = "Hakeem" },
    new { names = "Emily" },
    new { names = "Brenna" },
    new { names = "Maile" },
    new { names = "Beverly" },
    new { names = "Darrel" },
    new { names = "Rafael" },
    new { names = "Quon" },
    new { names = "Zeus" },
    new { names = "Edan" },
    new { names = "Chaim" },
    new { names = "Kenyon" },
    new { names = "Kennedy" },
    new { names = "Oscar" },
    new { names = "Hilda" },
    new { names = "Zeph" },
    new { names = "Abraham" },
    new { names = "Cruz" },
    new { names = "Alika" },
    new { names = "Ferris" },
    new { names = "Christopher" },
    new { names = "Candice" },
    new { names = "Burton" },
    new { names = "Clark" },
    new { names = "Keely" },
    new { names = "Upton" },
    new { names = "Grant" },
    new { names = "Richard" },
    new { names = "Wing" },
    new { names = "Kermit" },
    new { names = "Gay" },
    new { names = "Stephen" },
    new { names = "Tanner" },
    new { names = "Owen" },
    new { names = "Leroy" },
    new { names = "Marvin" },
    new { names = "Todd" },
    new { names = "Olga" },
    new { names = "Palmer" },
    new { names = "Kelsie" },
    new { names = "Ali" },
    new { names = "Simone" },
    new { names = "Hanae" },
    new { names = "Rana" },
    new { names = "Stewart" }
};

            var surname = new[] {
    new { surname = "Hays" },
    new { surname = "Tanner" },
    new { surname = "Rosales" },
    new { surname = "Mcdaniel" },
    new { surname = "Duffy" },
    new { surname = "Chapman" },
    new { surname = "Lawrence" },
    new { surname = "Clark" },
    new { surname = "Watkins" },
    new { surname = "Valentine" },
    new { surname = "Stokes" },
    new { surname = "Ryan" },
    new { surname = "Norris" },
    new { surname = "Knowles" },
    new { surname = "Lee" },
    new { surname = "Blackburn" },
    new { surname = "Cabrera" },
    new { surname = "Haney" },
    new { surname = "Ross" },
    new { surname = "Spears" },
    new { surname = "Dorsey" },
    new { surname = "Morin" },
    new { surname = "Gamble" },
    new { surname = "Mercer" },
    new { surname = "Mosley" },
    new { surname = "Ward" },
    new { surname = "Potts" },
    new { surname = "Mcgee" },
    new { surname = "Barry" },
    new { surname = "Herman" },
    new { surname = "Finch" },
    new { surname = "Rasmussen" },
    new { surname = "Flynn" },
    new { surname = "Gallagher" },
    new { surname = "Montgomery" },
    new { surname = "Henderson" },
    new { surname = "Horne" },
    new { surname = "Craft" },
    new { surname = "Baxter" },
    new { surname = "Moses" },
    new { surname = "Cote" },
    new { surname = "Santana" },
    new { surname = "Cooley" },
    new { surname = "Rosa" },
    new { surname = "Mcfadden" },
    new { surname = "Kramer" },
    new { surname = "Benjamin" },
    new { surname = "Hudson" },
    new { surname = "Franklin" },
    new { surname = "Pittman" },
    new { surname = "Jennings" },
    new { surname = "Fernandez" },
    new { surname = "Barlow" },
    new { surname = "Foreman" },
    new { surname = "Baldwin" },
    new { surname = "Browning" },
    new { surname = "Elliott" },
    new { surname = "Mosley" },
    new { surname = "Jordan" },
    new { surname = "Fitzgerald" },
    new { surname = "Knapp" },
    new { surname = "Guy" },
    new { surname = "Snyder" },
    new { surname = "Caldwell" },
    new { surname = "Cruz" },
    new { surname = "Cooke" },
    new { surname = "Burt" },
    new { surname = "Haley" },
    new { surname = "Steele" },
    new { surname = "Schneider" },
    new { surname = "Black" },
    new { surname = "Hurley" },
    new { surname = "Juarez" },
    new { surname = "Galloway" },
    new { surname = "Collins" },
    new { surname = "Fisher" },
    new { surname = "Mccullough" },
    new { surname = "Shannon" },
    new { surname = "Bradley" },
    new { surname = "Grimes" },
    new { surname = "Thompson" },
    new { surname = "Gaines" },
    new { surname = "Ford" },
    new { surname = "Juarez" },
    new { surname = "Bass" },
    new { surname = "Cobb" },
    new { surname = "Bishop" },
    new { surname = "Hogan" },
    new { surname = "Sexton" },
    new { surname = "Flowers" },
    new { surname = "Brown" },
    new { surname = "Walsh" },
    new { surname = "Robbins" },
    new { surname = "Kent" },
    new { surname = "Gentry" },
    new { surname = "Dalton" },
    new { surname = "Ball" },
    new { surname = "Cervantes" },
    new { surname = "Lee" },
    new { surname = "Marshall" }
};

            int i = 0;
            int j = 0;
            while (hash.size != kiekis - 1)
            {
                string temp = name[i].names + " " + surname[j].surname;
                hash.insert(getKey(name[i].names, surname[j].surname), temp);
                j++;
                if (j == 99) { i++; j = 0; }
                if (i == 99) { i = 0; }
            }
        }

        public string getKey(string name, string surname)
        {
            return name.Substring(0, 1) + surname.Substring(surname.Length - 1, 1) + surname.Substring(0, 1) + name.Substring(name.Length - 1, 1);
        }
    }
}
